### ISSUE TITLE
Official UnderStrap Feature Request List 

### ISSUE THREAD

**Issue by holger1411** [understrap/understrap#103]
According tto @stef-k suggestion I open up an "Feature Request" list here. Comment any idea you have below this post. Add your +1 if you like a specific comment/request. If it sounds good and useful I will add it to this list. 
Features should be useful for the majority of UnderStrap developers/users. So too specific feature requests (for example for a very uncommon plugin) will not be added. Sorry!

# Feature Requests / Bug Hunt Backlog:

## 0.5.0 release:
- [x] Page template with sidebar on the left (Discussions here: https://github.com/holger1411/understrap/issues/116)

- [x] Clean (numeric) page pagination (Discussions here: https://github.com/holger1411/understrap/issues/127)
- [x] More languages
- [x] Make functions pluggable
- [x] WooCommerce templates for product pages, category, checkout etc.
- [x] Fixing translation in author template (Discussions here: https://github.com/holger1411/understrap/issues/107)

## Ongoing task(s):
- [ ] Creating better/more docs - maybe with GitHub pages(?)  :tada: (Discussions here: 

## Backlog (future releases):
- [x] Fixing the gallery or create a new gallery script  (Discussions here: https://github.com/holger1411/understrap/issues/115)
- [ ] Page template with "hero" owl.carousel area
- [ ] Full RTL support 
- [ ] One / some child theme´s with a unique design (Discussions here: https://github.com/holger1411/understrap/issues/113)
- [x] Implement/check coding standards and HTML/SASS syntax according to WordPress standards 
Discussions here: https://github.com/holger1411/understrap/issues/118)

**Comment by stef-k** [comment]
I think it would be a good case to investigate and implement a flexible template that can be customized through the customizer api so that enables the user to choose left or right sidebar positioning.

**Comment by holger1411** [comment]
The problem with a customizer setting is that you have sidewide just left sidebars or right sidebars. May make sense for LTR or RTL sites as a general setting, but you can´t choose/change it based on a specific page... and what if you need a left AND right sidebar just in some cases?

**Comment by holger1411** [comment]
Maybe a general setting for the base template makes sense, but also adding custom templates for sepcial cases...will check some other WP themes and WP frameworks how they handle it.

**Comment by maxdmyers** [comment]
I've submitted PR #106 to resolve the feature request "Implement/check coding standards and HTML/SASS syntax according to @mdo ´s http://codeguide.co/" above.

**Comment by holger1411** [comment]
@stef-k: The problem with this solution is that it will work with 10 pages, maybe with 20 - 30 pages, but it will not be very usefull with 100+, 1000+, 10000+ pages...imagine you wanna test you page with all sidebars on the right instead on the left. You have to click a hundered times working down a looooong list.

So the basic approche should be like: Select a basic layout for all pages in your customizer (1. Sidebar on the left, 2. Sidebar on the right, 3. Sidebar on the left and right, 4. No sidebar).

Plus having special templates to overwrite this general setting by your page setup.
So you can change the global layout with just one click (doesnt matter if you have 3 pages or 3000+), but you have the option to change the layout for one or some specific pages if needed.

**Comment by stef-k** [comment]
@holger1411 thanks for the feedback, feel free to delete my comments.
thanks

**Comment by Thomas-A-Reinert** [comment]
@stef-k : great job requesting a feature request list! +5 for that ;)
@maxdmyers : Great job, really!
@holger1411 ´s last post: Yup, that should be the best approach. +1 on that. Need help with it?

As for the child theme unique style request. The question is: What would be highly recommended/requested? So I´d like to make a spin-off-thread to request what would be wanted within a child theme.

**Comment by holger1411** [comment]
Hi guys, I will add an own issue for any feature request from the list and link to it from the list.
I will be much easier to discuss and follow certain features.

@Thomas-A-Reinert : I hijacked your Issue #113 for the child theme thingy ;-)

**Comment by TomKisielewski** [comment]
Hi guys, some advice as I am not wordpress expert. I have built theme based on early understrap  and used dynamic widget areas. Code example:
this is not fully working stuff which I will dump soon
https://github.com/TomKisielewski/auxe/blob/master/widget-templates/top-widgets.php

My theme from link below needs some additional work but it works ( Bootstrap 3 )
theme demo: http://wabc.tkthemes.com/
and
description: http://www.tkthemes.com/free-templates/wordpress/wabc

I used understrap as a starter theme. As to sidebars ( widget areas) my approach is ok in Joomla, but not sure if it is correct in wordpress world. It does its purpose but all if/else logic in file makes me feel weird as it may affect performance. Could you please give me your opinion if you can
Tomasz

**Comment by stef-k** [comment]
A nice thing to have would be an overlay menu, covering the page when clicked, something like this http://www.wpbeginner.com/plugins/how-to-add-a-fullscreen-responsive-menu-in-wordpress/

Additionally another one would be an off canvas menu.

With those two and the native WordPress menu, users will have a wide range of options to use.

**Comment by stef-k** [comment]
A grid view for the archive page something like the following would be great

https://premium.wpmudev.org/blog/wp-content/uploads/2014/07/grid-desktop.png
![image](https://cloud.githubusercontent.com/assets/5731388/20112045/5fd13158-a5f3-11e6-93c2-0f9b04e41890.png)

Image and how to from: https://premium.wpmudev.org/blog/add-masonry-grid-layouts-to-your-wordpress-site-with-just-css/?utm_expid=3606929-90.6a_uo883STWy99lnGf8x1g.0&utm_referrer=https%3A%2F%2Fwww.google.gr%2F

**Comment by Confectrician** [comment]
## Second Right Floated Nav Menu

According to #124 I have also thought about registering a right floated second menu in general some time ago.

**Comment by Thomas-A-Reinert** [comment]
The customizer needs URGENT improvement!
Some functions as updating the site title for example won´t get displayed live.
Some other settings need to get integrated like text colors, link colors and many many more..

**Comment by stef-k** [comment]
@holger1411 I think the first item on the list should be checked as #116 is closed.

**Comment by stef-k** [comment]
@holger1411 I believe that 

> Implement/check coding standards and HTML/SASS syntax according to WordPress standards
Discussions here: #114)

should also reference  #118 since it is about standards.

**Comment by holger1411** [comment]
Changed. Thx!

**Comment by stef-k** [comment]
May I suggest that [we use trello for feature planning - tracking and voting](https://trello.com/tour)? 

This issue is already cluttered enough and won't handle much traffic.

**Comment by stef-k** [comment]
Proposed list item: integrate [Magnific popup](http://dimsemenov.com/plugins/magnific-popup/) JS library for lightboxes-zooming of images, its simple and tested

**Comment by stef-k** [comment]
Poposed list item: [Contact form 7](https://wordpress.org/plugins/contact-form-7/) integration for Bootstrap 4 classes currently having over 1 million installs making it a well tested tool and safe bet for Understrap to support it.

**Comment by stef-k** [comment]
@holger1411 any update about my latest comments?

- https://github.com/holger1411/understrap/issues/103#issuecomment-262174393
- https://github.com/holger1411/understrap/issues/103#issuecomment-262174707
- https://github.com/holger1411/understrap/issues/103#issuecomment-262175071

**Comment by saknopper** [comment]
I'll try to make a Dutch translation this week.

**Comment by holger1411** [comment]
Sorry for some reasons I did not get any infos about new comments in this issue.

To Trello:
Github offers Github projects which work much like Trello, but of course fully integrated into Github here. You can create Projects and than boards for it like this:
https://github.com/holger1411/understrap/projects

Seems very handy and you can use it in an agile style like a Scrum or Kanaban board

To Magnific PopUp: 
UnderStrap should stay a basic starter theme/framework without too much  stuff around and without too much dependencies. BS4 comes already with an PopUp component. So using a specific popup component of specific effects is more a question related to the guy builds up a ready-made and full designed theme on top of UnderStrap. Hope you understrand my intention...?

To Contact Form7:
Yep, sounds good. Used by millions, Contact Form 7 support, like WooCommerce support, make sense.
But I don´t know how clean the CF7 markup/frontend is and if we can overwrite it without too much support requests/bug´s ??? Maybe a very good starting point for the first Github project board ,-)
Added a Scrum-a-like board here:https://github.com/holger1411/understrap/projects/2

@saknopper You are welcome! Feel free to open a pull-request

**Comment by Thomas-A-Reinert** [comment]
@holger1411 seems i´m not able to edit or add anything to that list. is that a permission problem - which could be solved by taking some users into the group or upgrading their priviledges - or something else like that maybe?

**Comment by Thomas-A-Reinert** [comment]
@holger1411 , @stef-k and anyone else of the "core-contributors" or those who got some of the larger account of contributions.. Do we need an internal solution? I may be able to come up with something like that, but I do also think that we may need something like an **internal** communication toolkit to be more productive. Just a suggestion.

**Comment by holger1411** [comment]
@stef-k  and @Thomas-A-Reinert Invited you as Collaborator. Feel free to accept it and try if you could edit the project board.
And be carefull, the status as "collaborator" gives you full the full "pull power" ;-)

**Comment by Thomas-A-Reinert** [comment]
Sorry that ya´ll new assignees got "spammed" because I assigned you to this pretty old topic. But i think we should continue this thread and I´d like to have input from ya´ll. Some things already got fulfilled, others did not. And there´s quite a lot on my mind that should still be done.

What do you think?

**Comment by axlright** [comment]
@Thomas-A-Reinert thanks for the flurry of work and thanks as always @holger1411 

Looking through this list at the things my team uses a lot - a pop-up like @stef-k mentioned a while back is something pretty useful. We use [fancybox](https://fancyapps.com/fancybox/3/) which is easy to add via npm. I don't think it should be added into the js / css by default as it adds weight but if options are going to be added, this is an easy one. Seems nice to have it in the npm install so at least the files are there and updated.

Same thing for Owl - I've now added that to my team's package.json so the files are pulled / updated by npm to make it easier to add but I don't have it "on" by default because it adds a lot of weight to the js file.

I don't have any other suggestions off the bat.

I'd like to work on documentation where we can give basic instructions as well as a place for more advanced users to share tips and tricks.

I also like the idea stated somewhere above of a better repository for project examples. I get a lot of inspiration and solutions from looking at how others have achieved certain things in UnderStrap projects and try to share back to that. Would be cool to have an easier to use collection of project examples.

**Comment by GuerrillaCoder** [comment]
How do people feel about splitting things like carousels into a separate "Understrap Plugins" project?

We could then have a bit more freedom for adding in additional features that are optional and keep the core theme light.

**Comment by Thomas-A-Reinert** [comment]
@axlright As I started the whole thing, i kinda felt responsible improving it. And as i´ve been (desperately) waiting for client´s feedback today (which didn´t come up though and gave me some spare time therefore), i thought this is some kind of perfect timing..

I am also absolutely feeling with you - I´d also like to have fancybox (or comparable) and owl integrated into UnderStrap. But I also understand @holger1411 - who wants to keep it absolutely basic without any "bloat".

My suggestion - as a compromise - would be: As long as it doesn´t affect the "basic" theme - everything should be okay for holger. Can´t promise, that´s just an assumption. 
But i´d be willing to code something for the customizer if some more ppl would upvote this request and prevent default integration to keep that tight and lean.

I´d also count you in for the documentation project, @axlright - but thats up to @holger1411 to decide..

@GuerrillaCoder - interesting suggestion.  Can´t tell about the others, but i´d be totally okay with that - feels somehow like https://de.wordpress.org/plugins/siteorigin-panels/ with its pluggable API.

Anyway, if I - again - may put in my two cents - common issues and/or requests should be available through the core system. While still not bloat it. Hard to find any examples.. 
But let´s try: 
1.  Adjusting theme colors is MUST-HAVE these days I guess.
2. Including any "standard"-requests like fancybox and/or owl should be standard and/or adjustable via the customizer also.

Using a masonry-layout for frontpage and archives ( #135 ) therefore is an ADDON - at least to my feel. Altough this is a VERY cool feature for some sites ( a good load of my clients sites! ), but it cannot be called a "common request" and should therefore be handled through a plugin.

Anyway, plugins need maintenance and you´ll never know if/when a developer will drop the support for it. Keeping it "core" will almost ensure that it´s going to be maintained though.

As I said - just my two cent to try to keep the discussion up. Hope you understand? Anyway, thanks galore for you input. REALLY helpful!

**Comment by Thomas-A-Reinert** [comment]
ehrmpf. sorry. didn´t mean to close this issue..

**Comment by MarieComet** [comment]
Thank you for bringing up this old topic, I had not noticed until now.

What about Bootstrap Lightbox http://ashleydw.github.io/lightbox/ which propose a light support for gallery lightbox, based on Bootstrap ?
IMO Understrap as a starter theme should not embed more third-party solutions (even if they are good).
:+1: for https://github.com/understrap/understrap/pull/135, I never see this proposition before, an option to switch to grid style blog would be nice.

**Comment by holger1411** [comment]
According to this old issue I created a new project here:
https://github.com/orgs/understrap/projects
Its goal is to release UnderStrap 1.0.
I (and collaborators can do it too)will add tasks to it so we can work on it.

**Comment by GuerrillaCoder** [comment]
@Thomas-A-Reinert I think it would be a great idea, we just need to decide on a pattern.  The first thing I did when I started using understrap was delete all the carousel stuff and other things I didn't want (I'm not a fan of owl carousel).  Would be nice if we had a way where we could add third party stuff like grids, filters and carousels as optional dependencies.

**Comment by 0dp** [comment]
@axlright @GuerrillaCoder @Thomas-A-Reinert 
So in my process of coming up with a way to dynamically integrate FA4, FA5 free, or FA5 pro I have created a foundation for a node preinstall script, this script could potentially prompt the developer for all these extra features without having to add bloat to the actual theme. That could include adding features or removing them.
Another option could be a yeoman generator to scaffold new projects.

**Comment by axlright** [comment]
@Odp - node preinstall script sounds awesome. Seems like the best of all worlds - keep the base theme light and basic while offering options for developers. Excited to see how it works.

I personally feel like I need to understand two things in order to be an informed help to this community:

1) Who is the target audience? Is the theme for developers who know what BS4 and FA5 and npm and gulp is and want an awesome platform to build custom websites on? Or is the theme for people who would install it via WordPress theme installer, never run `npm install`, maybe add custom Sass that's compiled outside of the gulpfile workflow or maybe just add custom CSS on top of the theme CSS?

2) Speaking a bit to that, what is the intended relationship between the parent understrap theme and the understrap_child theme? Why does the child theme theme have all the vendor Sass and JS and need to be updated as often as the parent theme is? I think I understand the reason - so users who don't want to use gulp / npm can use the child theme out of the box. But I'm still not totally clear on the intended relationship between parent / child.

I'm super happy to direct my efforts at documentation and feature suggestion, and knowing more about those things will really help. I've been reading these threads for a while and I've been trying to get a handle on the above but I'm still not clear. 

Thanks!

**Comment by GuerrillaCoder** [comment]
@axlright I think people use this theme because it has bootstrap, gulp and is basic enough to be flexible.  It's definitely for developers.  If it goes down the road of appealing to non-devs with lots of database options then I think it will ruin it.

@0dp I am not sure about node pre-install script.  The JS/css files are just a small piece of the puzzle, the php code that implements it needs to be pluggable also.  I think splitting anything beyond base functionality to a plugin will probably be easier initially so we can get teething problems out of the way and work out a good pattern without messing up the theme then once it's organised merge it back into the theme if it makes sense.

**Comment by holger1411** [comment]
closing this because we are working on 0.82.
Feel free to open issues for the single topics.
