### ISSUE TITLE
Version 0.6.0 (or 1.0.0?) roadmap

### ISSUE THREAD

**Issue by holger1411** [understrap/understrap#205]
UnderStrap is now two years and one month old (inital commit was on Dec. 1st 2014  :tada:). 
Old enough to do the next step.
For the next major release I plan to put it on a more solid, cleaner and faster foundation.
That means reworking the stuff we already have and remove:
- Unneccessary Code
- Requests
- Querys
- Scripts
- Markup
- Overhead
- Remove features that did not really work or is used by miniority only.
etc.

The idea is to go back to a solid theme framework who supports the WP core (and some major Plugin like WooCommerce or CF7)...but not more.

~~Here are some ideas (feel free to add your own or to comment on mine):~~
## Milestones for 0.6.0: ##
- [x]  Removing the slider script (or capsule it very clean, or replacing it with the Bootstrap 4 default carousel) - I know a lot of people love sliders on there website...but in most cases Users don´t need/like em. So from a UX perspective they are not so cool. 
Status: **Was removed and replaced with a basic BS4 carousel implementation**

- [x]  Cleanup the markup and CSS - There are a lot of HTML/CSS and I´am not sure if they are used or usefull or it became obsolet meanwhile. 

- [ ]  Checking the WooCommerce integration - There are some bugs and layout glitches on some pages. And the theme checks if WooCommerce is active on any page request. Even if WooCommerce is not installed. Maybe a clean woocommerce.php file is the solution instead of incorporate it into non-woocommerce code.

- [x]  Check the latest WP and _s best practices and use/incorporate them.

- [x]  Check the latest WP 4.7 theme functions/features. 

- [x] Apply WordPress PHP coding standards ( https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/ ) and do automated tests (running via Travis CI, here: https://travis-ci.org/holger1411/understrap)

**Comment by schutzsmith** [comment]
I stumbled onto Understrap this morning and am loving what I see but with this shift in thinking, would you suggest we wait before using it in production environments? 

My concern is it sounds like these will be significant changes and I'd hate to launch in March only to discover a bunch of pieces we've relied on is gutted.

On the other hand, LOVE the concept of sticking to the _s core values of being a streamlined theme framework and not much more.

**Comment by holger1411** [comment]
Hi!
I think most issues above are just refactoring/cleanup work. So a productive enviroment will not be affected by it.
Maybe you have to edit one or two class names and test it on your staging before you deploy it to your live system ;-).

But it is good that you mentioned this topic ... I will keep the backwards compatibility in mind.

Only the slider decision might be a problem.
But I tend to keep this (or another) slider, but in a solid "capsule".
Means: If you don´t use it no line of extra code is loaded, if you use it you have one or two more requests.

**Comment by schutzsmith** [comment]
Thanks that is great to hear!

**Comment by alwaysalready** [comment]
I'm not sure how much work it would take, but I'd like some more options in _variables.scss that can then be customised in the _theme_variables.scss. I've found I can dig around the scss files to find some of the appropriate variables to customise, but this is a bit hit or miss and some css isn't customisable in this way. 

Just a small issue really as I've found workarounds and can always override the CSS. 

To answer your question about sliders, I'm not a real fan of them, but I guess they look good on the right site. I haven't figured out how to do it yet, but I'd like to use Owl Carousel to display some of my pictures in a small format, just so people can swipe through photos. 

Really happy with this theme and very grateful for all your work!!

**Comment by holger1411** [comment]
@alwaysalready Hm, there are hunderets of Bootstrap variables and to copy em to the theme_variables file makes just sense if you wanna change them. If not they can produce a lot of incompatibility issues if BS changes there variables.

The variable in _themes_variable.scss are just samples to outline how it works.
You can check the BS variables here:
https://github.com/twbs/bootstrap/blob/v4-dev/scss/_variables.scss

If you wanna change one just copy it to the _theme_variables.scss and replace the vlaues with yours

**Comment by alwaysalready** [comment]
Great tip. Thank you.

**Comment by ZXCVLuke** [comment]
I noticed you've removed the posts index styling? Any particular reason? I thought it was a useful feature.

**Comment by holger1411** [comment]
@ZXCVLuke: Was removed because of: https://github.com/holger1411/understrap/issues/211
The new BS4 Alpha 6 version with "flexbox-always-on" caused several bugs/problems.
I moved it to a feature branch. So we can merge it back as soon as there is a solution.

**Comment by coldfusion411** [comment]
@holger1411 - Yes. Yes. Yes. Get back to the roots and get rid of all the fluff. I initially started using Understrap because it was bare bones. There's nothing worse than having to remove functionality from the get go. 

1) Absolutely, there are tons of sliders out there if someone needs one. I see Understrap as a starter theme, not a feature theme. 

2) I feel like WooCommerce's template structure is the right direction.

3) I would consider adding dynamic sidebars to the them. Having to add a plugin for it is overkill.

Thanks! Will help where and when I can!

**Comment by marcodamm** [comment]
@holger1411 - I am not (yet) an active contributer but I used UnderStrap as the basis for some of my projects and I agree with all your points regarding encapsulating or even removing elements.

For the above mentioned projects I ended up removing owl-carusel styles and scripts, all of the woocommerce stuff, the hero widget lot's of unused bootstrap directives. This might seem drastic but it enabled me to boil down the size of a regular page to less than 180kb including about 70kb in image files.

Like @coldfusion411 if would therefore prefer a bare bones approach which gives me all the flexibility of _s and Bootstrap without all the fluff.

**Comment by typeplus** [comment]
I am also a fan of removing the slider and as much bootstrap stuff that isnt used. Has anyone had any luck with something like [PurifyCss](https://www.google.com.au/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=0ahUKEwjd3MbkjNzRAhVEbbwKHRrLBk8QFggZMAA&url=https%3A%2F%2Fgithub.com%2Fpurifycss%2Fpurifycss&usg=AFQjCNHkcBa-_Wojtso-3j9gjSckkCR73w&bvm=bv.145063293,d.dGc) or [uncss](https://github.com/ben-eb/gulp-uncss)? I haven't had much luck yetbut would anyone else actually be interested in this?

A dynamic solution rather than removing the source altogether would be a better idea in my opinion. Going by chrome inspector audit you can see most pages use very little of the src css files of bootstrap.

**Comment by holger1411** [comment]
Okay guys, ive done this (till now):
- removed the masonry function (was buggy after update to Bootstrap 4 Alpha 6 and saves some JS)

- removed the vertical page template

- replaced the OwlCarousel Slider with the default BS carousel. Lets me remove another dependency and save some CSS / JS and another extra request. 
If you don´t use it at all you can comment out this line:
`@import "../../src/sass/bootstrap4/carousel";`
in /sass/assets/bootstrap4 
to save some extra kb.

- Dynamize the static hero and footer full widget area. Means if you publish just one widget it will use the col-md-12 class, col-md-6 if you publish two widgets on the same position, col-md-4 if there are three widgets and so on.

- Boiling down the understrap scss file itself to just neccessary stuff. Saves just a few kb, but better than nothing

- Adding the new "edit icon in customizer view" function

-Adding some basic BS classes to the backend editor format dropdown

- Apply the themes CSS to the WP editor

**Comment by holger1411** [comment]
@typeplus I´am not sure something like uncss will work for a database driven cms theme framework.
The BS markup could be used in articles which will be stored in the database.
For example: The theme itself did not use any tables, so it would make sense to remove the table component with all the scss.
But as soon as anyone adds a table to a page or article the component is needed to provide responsive, Bootstrap-compatible table layout(s).

**Comment by typeplus** [comment]
@holger1411 that's what I thought too and I gave up but then someone pointed me to a "solution" that uses wordpress json data to tell uncss what is and isn't being used. I will keep trying but I reckon as you say the dynamic aspect of the db will always cause something to not be detected by these apps. This is all minor stuff though, sorry if i came across as someone complaining that there was not enough caviar on my truffles. This project is so so great as it is 👍

**Comment by flyingchorse** [comment]
@holger1411 This all sounds good. I am all for a well put together baseline theme that you can add extra functionality to if you want to.

I have an issue with the carousel [implementation](https://github.com/holger1411/understrap/issues/243) now though

**Comment by ZXCVLuke** [comment]
@holger1411 I've been using Understrap for my first project for the last couple of months (part time) and have been very impressed. Your list above looks promising. I have actually learnt quite a bit from seeing how you've pieced all of it together. Thanks.

I'm glad your extending my suggestion of BS classes in the editor. BS is a framework for building web apps and this allows users to make use of many of the features that would otherwise just be bloat. I'm also glad that you're going to set up an editor-styles.css file. I have done the editor styles manually for this one job of mine, but I hope you can find a more clever way of doing it, perhaps using gulp?

I imagine it's a hard balance with a starter theme like this to determine whether to include something or not. Someone will always have to tear a part of it back out for their project, while someone else will be upset when you remove a part of it that they have been using. Perhaps making sure that all of the parts are somewhat modular and are easy to remove (and add back in later) for those projects that don't need them? The core I guess is Underscores and Bootstrap. I'd like it if everything else was easy to remove.

I would suggest to @marcodamm and @typeplus that if they are concerned by all of the unused BS styles perhaps they could get into sass/assets/bootstrap4.scss and comment out the components their theme isn't using. It's not so straightforward for the scripts though. Perhaps even reconsidering the use of a BS-based starter might be appropriate? As I mentioned above it's often not the best framework for WordPress sites.

I, myself have torn out Owl Carousel, Contact Form 7, the theme settings for container and post index style, all of the user-selected page templates, sidebars and widget areas. My clients aren't WP experts so keeping it simple and prescriptive is best for me. I'm using everything else and for this one have added a JS Instagram feed, my own extra theme functions file, a couple of loop templates, a few custom page templates, and some global templates. 

I am glad you have kept the WooCommerce integration. I would suggest having a _theme-woocommerce.scss file to handle Woocommerce styles. It'd be great if some of the woo styles were set up initially to pull styles from the _theme-variables.scss. If I get a chance in the coming months I'll have a crack at it myself and do a pull request.

Thanks again for sharing your hard work with us.

**Comment by stef-k** [comment]
Coming back to add something I have experienced these past months.

In its current state bootstrap is not to be trusted with production work which it is totally reasonable as an alpha release. We saw many changes some small other big who broke things (see the switch to flexbox).

With this in mind, and having limited time to fix future changes and regressions, I propose to hold the talk for an 1.0.0 release  until Bootstrap reaches at least in a release candidate version.

This way we can be sure that any work done will be permanent and not based on experimental features.

**Comment by holger1411** [comment]
@stef-k: Understand your point.

My plan is to release UnderStrap 1.0 not until BS4 is stable, too.
Untill than I will try to boil it down to a rock solid foundation ... but with less /as little as possible features outside the WP and BS core stuff.

So if the Bootstrap guys do one step we just have to do the same one step and don´t have to rebuild entire components/features.

**Comment by 0dp** [comment]
@holger1411 is this still relevant?

**Comment by holger1411** [comment]
@0dp Can be closed ;-)
